// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS configuration is missing. Please run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS configuration is missing. Please run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows configuration is missing. Please run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux has not been configured for this project.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkx4lpCm4dmnV3DBULQdazPq3L3Gwpj8',
    appId: '1:573709156651:android:905129518f24b06f13856e',
    messagingSenderId: '573709156651',
    projectId: 'urbanstay-8f9e7',
    storageBucket: 'urbanstay-8f9e7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeP3wLOqVdg35andcJWciOETQ6jGvMkWU',
    appId: '1:573709156651:web:87afda9a4474972f13856e',
    messagingSenderId: '573709156651',
    projectId: 'urbanstay-8f9e7',
    authDomain: 'urbanstay-8f9e7.firebaseapp.com',
    storageBucket: 'urbanstay-8f9e7.firebasestorage.app',
    measurementId: 'G-D220D1H867',
  );

}